import styles from './styles.module.scss';

export default function dashboard(props) {

    // navbar = `${props.isNavOpen ? styles.nav_close : styles.nav_open}`; 

    return (
        <section className={`${styles.dashboard} ${props.isNavOpen ? styles.navOpen : ''}`}>
            <div className={styles.header}>
                <div className={styles.titleLeftArea}>
                    <span className={styles.headerTitle}>Dashbobard</span>
                    <span className={styles.headerTitleDescription}>Painel de Indicadores para acompanhamento estratégico</span>
                </div>
            </div>
            <div className={styles.body}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus vel ultricies nibh. Aenean fringilla odio orci, sed finibus libero ultricies ut. Nunc facilisis sed nisi quis consequat. Nulla finibus neque nec ante tristique, a luctus diam ultricies. Sed faucibus sem ipsum, et dictum lacus maximus in. Suspendisse ac porttitor velit, efficitur iaculis felis. Aliquam mauris libero, rhoncus bibendum laoreet et, posuere sed sapien. Nullam diam massa, aliquet et tortor a, vulputate rutrum ex. Aenean ut urna non ex tincidunt porta porttitor eget lectus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam ac imperdiet eros. Aliquam tristique orci vitae nisi lobortis pharetra. Phasellus semper condimentum consectetur. Integer tempus erat nisi, a finibus ante mollis at. Sed sollicitudin fringilla turpis eget rutrum.</p>
            <p>Nunc accumsan enim a vulputate dignissim. Aliquam ligula metus, maximus ut interdum a, elementum ac arcu. Nunc non semper ligula. Etiam diam leo, faucibus varius venenatis id, dignissim ac ex. Vestibulum arcu libero, faucibus eget metus vel, laoreet porttitor mi. Pellentesque molestie sem ac congue rutrum. Praesent elit libero, posuere id efficitur eget, pellentesque ut mi. Praesent feugiat tempor sem id venenatis. Proin hendrerit, augue sed porta porta, est nisi ultrices sapien, et dignissim risus leo nec neque. Vestibulum id sem ac nulla facilisis euismod. Aenean sollicitudin cursus purus, ac pellentesque mi vestibulum non. Fusce vel iaculis nisl. Pellentesque ut consectetur dolor, in volutpat mi.</p>
            <p>Vivamus eu ipsum id metus bibendum viverra. Cras pulvinar vitae erat et ultrices. Morbi gravida auctor augue. Phasellus vel nulla ac ligula ultrices viverra. Etiam ante est, porttitor et nunc sit amet, sodales ullamcorper erat. Pellentesque fermentum, arcu at mollis mattis, ipsum elit congue lacus, quis molestie ex est eu nibh. Curabitur sagittis nulla a neque maximus, sed ornare odio rhoncus. Nunc commodo lacus et eros convallis, et commodo turpis gravida. Nunc ullamcorper ligula risus, in vulputate est dignissim vitae. Sed consectetur dolor tortor, tempor iaculis purus tristique id. Pellentesque a enim sit amet lacus ultricies condimentum. Duis a commodo diam, nec sollicitudin ante. Donec tempor dui et congue hendrerit.</p>
            <p>Morbi et pellentesque leo, sed egestas urna. Ut ac sodales leo. Praesent hendrerit velit quis cursus sagittis. Vestibulum tincidunt orci vitae sodales rhoncus. Aenean vitae dui est. Sed lectus ligula, mattis sit amet scelerisque sit amet, vestibulum nec erat. Nullam non tortor non felis vestibulum varius lacinia quis ex. Nulla a risus nulla. Phasellus efficitur dolor eget laoreet ullamcorper. Sed finibus lacinia ex id malesuada. Nullam non congue erat, quis dapibus libero.</p>
            <p>Sed sed nisi auctor, tempor sapien quis, blandit massa. Quisque in felis rutrum, pellentesque augue sit amet, elementum ligula. Ut luctus elit vitae magna tristique, sed ornare sapien dapibus. Quisque dapibus, urna vitae venenatis tincidunt, nulla urna tincidunt ipsum, non auctor ligula lacus sed nisl. Sed elementum, neque eget auctor ultricies, massa felis semper neque, vitae convallis sem ex in nunc. Nunc nec feugiat justo. Aenean tempus imperdiet sodales. Donec ut metus ac nunc vulputate vestibulum ut quis augue. Mauris interdum velit ac posuere pharetra.</p>
            <p>Aenean et rutrum dui, nec blandit ligula. Vestibulum finibus neque at luctus fermentum. Nam imperdiet arcu metus, nec posuere nisi eleifend id. In a lacinia felis. Nullam sed sapien eros. Nullam luctus libero scelerisque, iaculis leo eu, venenatis quam. Phasellus tempus elit eget quam dignissim pulvinar. Nullam urna mi, scelerisque eu varius sodales, ultrices sed massa. Praesent nec tincidunt elit, nec tempus turpis.</p>
            <p>Maecenas dolor sapien, iaculis at felis id, viverra ultricies massa. Cras nec dignissim neque. Sed tempor lacus turpis, et bibendum mi laoreet a. Etiam et enim et purus blandit finibus. Proin tortor erat, semper feugiat aliquet quis, commodo eget ante. Cras ultrices, nulla quis efficitur pharetra, nibh orci scelerisque quam, et rhoncus eros eros ut magna. Proin vitae turpis sodales, bibendum est in, convallis augue. Sed porta auctor nunc, id pulvinar mauris dictum sed. Pellentesque ut sollicitudin eros.</p>
            <p>Nullam laoreet imperdiet viverra. Quisque laoreet neque turpis, a lacinia felis euismod eget. Nulla varius feugiat dui non blandit. Morbi vestibulum finibus ex in fermentum. Morbi at nibh ultrices, sollicitudin justo eget, vestibulum mi. Sed quis orci non augue pharetra vestibulum eget nec sem. Cras eu eros risus. Duis vitae vestibulum ipsum. Sed mattis, urna at rhoncus pretium, mi lorem pretium elit, ac mattis risus purus eget sem. Proin id feugiat diam. Cras sem urna, fermentum eu arcu non, cursus ullamcorper purus. Vestibulum sit amet molestie purus.</p>
            <p>Nunc accumsan enim a vulputate dignissim. Aliquam ligula metus, maximus ut interdum a, elementum ac arcu. Nunc non semper ligula. Etiam diam leo, faucibus varius venenatis id, dignissim ac ex. Vestibulum arcu libero, faucibus eget metus vel, laoreet porttitor mi. Pellentesque molestie sem ac congue rutrum. Praesent elit libero, posuere id efficitur eget, pellentesque ut mi. Praesent feugiat tempor sem id venenatis. Proin hendrerit, augue sed porta porta, est nisi ultrices sapien, et dignissim risus leo nec neque. Vestibulum id sem ac nulla facilisis euismod. Aenean sollicitudin cursus purus, ac pellentesque mi vestibulum non. Fusce vel iaculis nisl. Pellentesque ut consectetur dolor, in volutpat mi.</p>
            <p>Vivamus eu ipsum id metus bibendum viverra. Cras pulvinar vitae erat et ultrices. Morbi gravida auctor augue. Phasellus vel nulla ac ligula ultrices viverra. Etiam ante est, porttitor et nunc sit amet, sodales ullamcorper erat. Pellentesque fermentum, arcu at mollis mattis, ipsum elit congue lacus, quis molestie ex est eu nibh. Curabitur sagittis nulla a neque maximus, sed ornare odio rhoncus. Nunc commodo lacus et eros convallis, et commodo turpis gravida. Nunc ullamcorper ligula risus, in vulputate est dignissim vitae. Sed consectetur dolor tortor, tempor iaculis purus tristique id. Pellentesque a enim sit amet lacus ultricies condimentum. Duis a commodo diam, nec sollicitudin ante. Donec tempor dui et congue hendrerit.</p>
            <p>Morbi et pellentesque leo, sed egestas urna. Ut ac sodales leo. Praesent hendrerit velit quis cursus sagittis. Vestibulum tincidunt orci vitae sodales rhoncus. Aenean vitae dui est. Sed lectus ligula, mattis sit amet scelerisque sit amet, vestibulum nec erat. Nullam non tortor non felis vestibulum varius lacinia quis ex. Nulla a risus nulla. Phasellus efficitur dolor eget laoreet ullamcorper. Sed finibus lacinia ex id malesuada. Nullam non congue erat, quis dapibus libero.</p>
            <p>Sed sed nisi auctor, tempor sapien quis, blandit massa. Quisque in felis rutrum, pellentesque augue sit amet, elementum ligula. Ut luctus elit vitae magna tristique, sed ornare sapien dapibus. Quisque dapibus, urna vitae venenatis tincidunt, nulla urna tincidunt ipsum, non auctor ligula lacus sed nisl. Sed elementum, neque eget auctor ultricies, massa felis semper neque, vitae convallis sem ex in nunc. Nunc nec feugiat justo. Aenean tempus imperdiet sodales. Donec ut metus ac nunc vulputate vestibulum ut quis augue. Mauris interdum velit ac posuere pharetra.</p>
            <p>Aenean et rutrum dui, nec blandit ligula. Vestibulum finibus neque at luctus fermentum. Nam imperdiet arcu metus, nec posuere nisi eleifend id. In a lacinia felis. Nullam sed sapien eros. Nullam luctus libero scelerisque, iaculis leo eu, venenatis quam. Phasellus tempus elit eget quam dignissim pulvinar. Nullam urna mi, scelerisque eu varius sodales, ultrices sed massa. Praesent nec tincidunt elit, nec tempus turpis.</p>
            <p>Maecenas dolor sapien, iaculis at felis id, viverra ultricies massa. Cras nec dignissim neque. Sed tempor lacus turpis, et bibendum mi laoreet a. Etiam et enim et purus blandit finibus. Proin tortor erat, semper feugiat aliquet quis, commodo eget ante. Cras ultrices, nulla quis efficitur pharetra, nibh orci scelerisque quam, et rhoncus eros eros ut magna. Proin vitae turpis sodales, bibendum est in, convallis augue. Sed porta auctor nunc, id pulvinar mauris dictum sed. Pellentesque ut sollicitudin eros.</p>
            <p>Nullam laoreet imperdiet viverra. Quisque laoreet neque turpis, a lacinia felis euismod eget. Nulla varius feugiat dui non blandit. Morbi vestibulum finibus ex in fermentum. Morbi at nibh ultrices, sollicitudin justo eget, vestibulum mi. Sed quis orci non augue pharetra vestibulum eget nec sem. Cras eu eros risus. Duis vitae vestibulum ipsum. Sed mattis, urna at rhoncus pretium, mi lorem pretium elit, ac mattis risus purus eget sem. Proin id feugiat diam. Cras sem urna, fermentum eu arcu non, cursus ullamcorper purus. Vestibulum sit amet molestie purus.</p>
            </div>
        </section>
    );
}